### ISSUE TITLE
Mobile: Home Page needs a bit of spacing after services.

### ISSUE THREAD

**Issue by dcbartlett** [BushidoStudios/bushidostudios.github.io#14]
Home Page needs a bit of spacing after services.  Currently the last few services are almost right up against the "Software We've Built" section and would look better with a bit of space.

![image](https://user-images.githubusercontent.com/1077050/26863111-2217b6c0-4b16-11e7-808f-32b1cad0def3.png)

**Comment by theguy404** [comment]
spacing has been adjusted.

**Comment by dcbartlett** [comment]
Approved
