### ISSUE TITLE
Tablet: Call To Action too far to right.

### ISSUE THREAD

**Issue by dcbartlett** [BushidoStudios/bushidostudios.github.io#16]
The Call to action seems to be off-center.  This need to be centered up.  For Tablet and Mobile, the button should be under the text.  It looks like the button has a fixed width and gets pushed off screen.

![image](https://user-images.githubusercontent.com/1077050/26945509-9ace0e66-4c51-11e7-89d5-ad975c8ed6ba.png)

**Comment by theguy404** [comment]
can't reproduce error
