### ISSUE TITLE
Mobile: Bring social media icons out of the menu, and into the menu-bar

### ISSUE THREAD

**Issue by dcbartlett** [BushidoStudios/bushidostudios.github.io#7]
Bring social media icons out of the menu, and into the menu-bar.  This will bring our social presence to the user more quickly.

**Comment by theguy404** [comment]
social media buttons have been added to menu bar now.

**Comment by dcbartlett** [comment]
The social media icons should be brought to the right of the nav bar up next to the menu icon.  I should have clarified that better when i asked for the change.

**Comment by theguy404** [comment]
the icons now hug the menu button.

**Comment by dcbartlett** [comment]
Approved
